services:
  db:
    image: postgres:17
    restart: always
    expose:
      - 5432
    # ports:
    #   - 5432:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: bind
        source: ./migrations/000001_create_db.up.sql
        target: /docker-entrypoint-initdb.d/000001_create_db.up.sql
  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file: .env
    restart: always

volumes:
  db-data:
